### ISSUE TITLE
MalformedURLException while using StubbyClient's startJetty method

### ISSUE THREAD

**Issue by RobinSmit** [azagniotov/stubby4j#88]
Hi all,

I'm getting a MalformedURLException when i use the startJetty method from the StubbyClient.
It may be possible that i'm not initializing Stubby the right way.

```

private StubbyClient stubbyClient = new StubbyClient();            
private static final String STUB_YAML_LOC = "stubdata.yml";

public void startStub() {            
    stubbyClient.startJetty(STUB_YAML_LOC);
}
```

Can someone please tell me why that exception occurs?

**STACKTRACE:**
```
17:35:47.799 [main] ERROR eu.something.sys.something.ka.test.automation.library.Stubby - Error while preparing Stubby
java.net.MalformedURLException: For input string: "8882^"
	at java.net.URL.<init>(URL.java:627)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at io.github.azagniotov.stubby4j.http.StubbyHttpTransport.getResponse(StubbyHttpTransport.java:78)
	at io.github.azagniotov.stubby4j.client.StubbyClient.makeRequest(StubbyClient.java:508)
	at io.github.azagniotov.stubby4j.client.StubbyClient.doPost(StubbyClient.java:328)
	at io.github.azagniotov.stubby4j.client.StubbyClient.doPostUsingDefaults(StubbyClient.java:357)
	at io.github.azagniotov.stubby4j.client.StubbyClient.doPostUsingDefaults(StubbyClient.java:341)
	at eu.something.sys.something.ka.test.automation.library.Stubby.prepareStubWithProducts(Stubby.java:30)
	at eu.something.sys.something.ka.test.stepdefs.StubStepDefs.lambda$new$0(StubStepDefs.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:32)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:26)
	at cucumber.runtime.java8.Java8StepDefinition.execute(Java8StepDefinition.java:106)
	at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:40)
	at cucumber.api.TestStep.executeStep(TestStep.java:102)
	at cucumber.api.TestStep.run(TestStep.java:83)
	at cucumber.api.TestCase.run(TestCase.java:58)
	at cucumber.runner.Runner.runPickle(Runner.java:80)
	at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:140)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:117)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:55)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:126)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.NumberFormatException: For input string: "8882^"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at java.net.URLStreamHandler.parseURL(URLStreamHandler.java:222)
	at java.net.URL.<init>(URL.java:622)
	... 46 common frames omitted
```

**Comment by azagniotov** [comment]
Hi Robin,

How does your "stubdata.yml" look like?

It looks like there was a problem getting response, so what kind of request
are you making, what API on "StubbyClient" are you invoking? what
parameters are you passing?

P.S. Traveling now, please allow longer response times

**Comment by RobinSmit** [comment]
Thanks for your quick reply.
The issue seems resolved after a reboot. It could have been a hanging process that used the same port.
